### ISSUE TITLE
ruby hooks fail with: bzip2 not found

### ISSUE THREAD

**Issue by mishaschwartz** [pre-commit-ci/runner-image#162]
After the upgrade from ubuntu jammy (from focal), it looks like the bzip2 package is no longer available for pre-commit CI builds. 

I believe that my required ruby language version (2.7.0) is being downloaded as a `.tar.bz2` file but cannot be extracted so the hook set up is failing. 

My guess is that jammy may not have bzip2 available by default so it may need to be installed separately in the Dockerfile but this is just an initial guess.

Here is the relevant section of my `.pre-commit-config.yaml` file:

```yaml
  - repo: https://github.com/rubocop/rubocop
    rev: v1.36.0
    hooks:
      - id: rubocop
        language_version: 2.7.0
        args: ["--autocorrect"]
        types: ["ruby"]
        exclude: |
          (?x)^(
            db/migrate/.*|
            db/schema.rb|
            lib/repo/test/.*
          )$
        additional_dependencies:
          - rubocop-rails:2.13.2

```

And here is the output of one of the failing pre-commit CI runs that shows the error message:

https://results.pre-commit.ci/run/github/940538/1667297031.sRXrKZCtT86jrIIC5uUsYQ

Thank you for your help!
